/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 car.gltf 
Author: BHP3D (https://sketchfab.com/BHP3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2018-ford-everestendeavour-a6681649d203483c95239c4b73157697
Title: 2018 Ford Everest/Endeavour
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 122.881, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.861, 1.812, -0.713]}>
            <group position={[0, 0, -0.072]}>
              <mesh geometry={nodes.roda_roda0_0.geometry} material={materials['roda.0']} />
              <mesh geometry={nodes.roda_roda1_0.geometry} material={materials['roda.1']} />
            </group>
            <group position={[0, -2.909, -0.098]}>
              <mesh geometry={nodes.roda001_roda0_0.geometry} material={materials['roda.0']} />
              <mesh geometry={nodes.roda001_roda1_0.geometry} material={materials['roda.1']} />
            </group>
            <group position={[-1.722, 0, -0.072]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.roda002_roda0_0.geometry} material={materials['roda.0']} />
              <mesh geometry={nodes.roda002_roda1_0.geometry} material={materials['roda.1']} />
            </group>
            <group position={[-1.722, -2.909, -0.098]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.roda003_roda0_0.geometry} material={materials['roda.0']} />
              <mesh geometry={nodes.roda003_roda1_0.geometry} material={materials['roda.1']} />
            </group>
          </group>
          <group position={[0.987, 0.099, -0.388]}>
            <mesh geometry={nodes.door_rr_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.door_rr_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.door_rr_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.door_rr_ok_glass_0.geometry} material={materials.glass} />
          </group>
          <group position={[-0.951, 0.097, -0.371]}>
            <mesh geometry={nodes.door_lr_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.door_lr_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.door_lr_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.door_lr_ok_glass_0.geometry} material={materials.glass} />
          </group>
          <group position={[0.958, 1.2, -0.349]}>
            <mesh geometry={nodes.door_rf_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.door_rf_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.door_rf_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.door_rf_ok_glass_0.geometry} material={materials.glass} />
          </group>
          <group position={[-0.964, 1.193, -0.362]}>
            <mesh geometry={nodes.door_lf_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.door_lf_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.door_lf_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.door_lf_ok_glass_0.geometry} material={materials.glass} />
          </group>
          <group position={[-0.992, -1.585, -0.471]}>
            <mesh geometry={nodes.bump_rear_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.bump_rear_ok_primary_0.geometry} material={materials.primary} />
          </group>
          <group position={[0.947, 2.283, -0.32]}>
            <mesh geometry={nodes.bump_front_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.bump_front_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.bump_front_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.bump_front_ok_glass001_0.geometry} material={materials['glass.001']} />
          </group>
          <group position={[0, 1.437, 0.123]}>
            <mesh geometry={nodes.bonnet_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.bonnet_ok_primary_0.geometry} material={materials.primary} />
          </group>
          <group position={[0, -1.679, 0.554]}>
            <mesh geometry={nodes.boot_ok_interior0_0.geometry} material={materials['interior.0']} />
            <mesh geometry={nodes.boot_ok_interior1_0.geometry} material={materials['interior.1']} />
            <mesh geometry={nodes.boot_ok_primary_0.geometry} material={materials.primary} />
            <mesh geometry={nodes.boot_ok_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.boot_ok_grade2_0.geometry} material={materials['grade.2']} />
            <mesh geometry={nodes.boot_ok_boot_ok4_0.geometry} material={materials['boot_ok.4']} />
          </group>
          <mesh geometry={nodes.interior_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.interior_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.bancos_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.bancos_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.volante_interior0_0.geometry} material={materials['interior.0']} position={[-0.46, 0.808, -0.067]} rotation={[-0.33, 0, 0]} />
          <mesh geometry={nodes.estribo_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.estribo_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.grade_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.grade_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.grade_grade2_0.geometry} material={materials['grade.2']} />
          <mesh geometry={nodes.motor_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.motor_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.suspens_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.chassis_interior0_0.geometry} material={materials['interior.0']} />
          <mesh geometry={nodes.chassis_interior1_0.geometry} material={materials['interior.1']} />
          <mesh geometry={nodes.chassis_primary_0.geometry} material={materials.primary} />
          <mesh geometry={nodes.chassis_glass_0.geometry} material={materials.glass} />
          <mesh geometry={nodes.chassis_glass001_0.geometry} material={materials['glass.001']} />
          <mesh geometry={nodes.chassis_boot_ok4_0.geometry} material={materials['boot_ok.4']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
